resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/budo-web
  newName: ghcr.io/harris-consult/budo-web
  newTag: 0815b5d1c94c24c9654ded7f5be3a0616012d292
