resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/budo-web
  newName: ghcr.io/harris-consult/budo-web
  newTag: 7ab11f91d4dc641136aff307799b24c3d732ed81
