resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/budo-web
  newName: ghcr.io/harris-consult/budo-web
  newTag: e0c2fb88e918eea6d2efb7f530b45c1235ac7408
