resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-auth
  newName: ghcr.io/harris-consult/schoolrider-auth
  newTag: 5103a30cb3c34476b5800b7427ed6c29ae3288f1
