resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-auth
  newName: ghcr.io/harris-consult/schoolrider-auth
  newTag: d9ac73b4a984d9d26706c428b3b213635248f68f
