resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-auth
  newName: ghcr.io/harris-consult/schoolrider-auth
  newTag: 4a27e4be88b2a386088f2a81e0804ab9aa83ea30
