resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/cradle-website
  newName: ghcr.io/harris-consult/cradle-website
  newTag: e8424d9d2f7cea234723e25b58186f92d0a487b1
