apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tkproster-firebase-sync
  namespace: tkproster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: global-gcp-store
    kind: ClusterSecretStore
  target:
    name: tkproster-secrets
    creationPolicy: Merge
  data:
    - secretKey: FIREBASE_CONFIG
      remoteRef:
        key: tkproster-fcm-secret
