apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tkp-traffic-api-sync
  namespace: tkp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: tkp-traffic-secrets
    creationPolicy: Merge
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        MONGO_URI: "mongodb://{{ .MONGO_USER }}:{{ .MONGO_PASSWORD }}@{{ .MONGO_HOST }}:{{ .MONGO_PORT }}/tkproster?authSource=admin"
        JWT_EXPIRES_IN: "7d"

  data:
    - secretKey: MONGO_USER
      remoteRef:
        key: global-db-secrets
        property: MONGO_USER
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: global-db-secrets
        property: MONGO_PASSWORD
    - secretKey: MONGO_HOST
      remoteRef:
        key: global-db-secrets
        property: MONGO_HOST
    - secretKey: MONGO_PORT
      remoteRef:
        key: global-db-secrets
        property: MONGO_PORT
