resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/tkp-traffic-api
  newName: ghcr.io/harris-consult/tkp-traffic-api
  newTag: c1833dccc65ec45e65f05050fef7944f699a9fbc
