resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/tkp-traffic-api
  newName: ghcr.io/harris-consult/tkp-traffic-api
  newTag: 32d8a435d1ebb478b1bbee8e1978bcffedb039fe
