resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/tkp-traffic-api
  newName: ghcr.io/harris-consult/tkp-traffic-api
  newTag: f0f872d64d455b2271c479a121247060feb71a41
