resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-landing
  newName: ghcr.io/harris-consult/schoolrider-landing
  newTag: 66b462516db497d8cf3b786a2be94a40bb0ce8a3
