resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-landing
  newName: ghcr.io/harris-consult/schoolrider-landing
  newTag: 3fa15326e3334a6fa5db93978efdfb8986260838
