resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-landing
  newName: ghcr.io/harris-consult/schoolrider-landing
  newTag: a97873a377a76b18cce2ac4518bd6ec81c01e359
