resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/blue-vision-app
  newName: ghcr.io/harris-consult/blue-vision-app
  newTag: 0e49d28b01f408341b099e7725cf8c4248b7c145
