resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/blue-vision-app
  newName: ghcr.io/harris-consult/blue-vision-app
  newTag: 7839dfd36d50640b411aca11c4c681bbda9b65c7
