resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-admin
  newName: ghcr.io/harris-consult/schoolrider-admin
  newTag: f46ec15c15aa0e244ade23df8f7ec63f2c51aea5
