resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-admin
  newName: ghcr.io/harris-consult/schoolrider-admin
  newTag: 10a0975bc14f35a904893478eb07db054c427913
