resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-admin
  newName: ghcr.io/harris-consult/schoolrider-admin
  newTag: 913f039011fa71dadfdf5eedc36722460150be27
