apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-vision-api
  namespace: blue-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-vision-api
  template:
    metadata:
      labels:
        app: blue-vision-api
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: blue-vision-api

      containers:
      - name: blue-vision-api
        image: ghcr.io/harris-consult/blue-vision-api:latest
        ports:
        - containerPort: 3000

        envFrom:
        - secretRef:
            name: blue-vision-secrets
