apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-vision-api
  namespace: blue-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-vision-api
  template:
    metadata:
      labels:
        app: blue-vision-api
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: blue-vision-api

      # initContainers:
      #   - name: mongo-reset
      #     image: mongo:7
      #     command: ["/bin/sh", "-c"]
      #     args:
      #       - |
      #         echo "Waiting for MongoDB..."
      #         until mongosh "$MONGO_URI" --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; do
      #           sleep 2
      #         done

      #         echo "🔄 Resetting MongoDB database..."
      #         mongosh "$MONGO_URI" --eval "db.dropDatabase()"
      #         echo "✅ MongoDB reset complete."
      #     envFrom:
      #       - secretRef:
      #           name: blue-vision-secrets

      containers:
        - name: blue-vision-api
          image: ghcr.io/harris-consult/blue-vision-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: blue-vision-secrets
          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 5000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
