resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-app
  newName: ghcr.io/harris-consult/schoolrider-app
  newTag: 2840cc23f1d6447e93380af840874422eb2e37d0
