resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-app
  newName: ghcr.io/harris-consult/schoolrider-app
  newTag: 50083ad66fe3c5d1a17395199b8159a875128231
