resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-app
  newName: ghcr.io/harris-consult/schoolrider-app
  newTag: cc948dbafea0a0df654af0a10b630b459fb31a9a
