resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/budo-app
  newName: ghcr.io/harris-consult/budo-app
  newTag: e02a20e9d3612b33edfe02e26b5e806a565afb14
