resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/budo-app
  newName: ghcr.io/harris-consult/budo-app
  newTag: 086ee00ca7c91e3158c3334e4cb976294253b06c
