resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/budo-app
  newName: ghcr.io/harris-consult/budo-app
  newTag: bbc21eaaa2770b202a28775f49e266d7ca3bfabb
