apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolrider-admin
  namespace: schoolrider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schoolrider-admin
  template:
    metadata:
      labels:
        app: schoolrider-admin
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: schoolrider-admin

      containers:
      - name: schoolrider-admin
        image: ghcr.io/harris-consult/schoolrider-admin:latest
        ports:
        - containerPort: 9015

        envFrom:
        - secretRef:
            name: schoolrider-secrets