resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/cradle-web
  newName: ghcr.io/harris-consult/cradle-web
  newTag: 0bb07c94e8bcb60b920848503e1fae932f8c55c5
