resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/cradle-web
  newName: ghcr.io/harris-consult/cradle-web
  newTag: 85ca281255dbd686597649b78f4f40c721f951e5
