resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/cradle-web
  newName: ghcr.io/harris-consult/cradle-web
  newTag: e3dd020499d65cbd9783ade994b1136f7f26dcc2
