resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/blue-vision-api
  newName: ghcr.io/harris-consult/blue-vision-api
  newTag: dde5f0458a002adab3df1ae98ce486c4eb93b4a2
