resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/blue-vision-api
  newName: ghcr.io/harris-consult/blue-vision-api
  newTag: 305fdd5ad4e9277ac757ea13d2853f4ba236ecd8
