resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/blue-vision-api
  newName: ghcr.io/harris-consult/blue-vision-api
  newTag: b830b791e68b928a5b9278c604d83afa05b87d8b
