apiVersion: apps/v1
kind: Deployment
metadata:
  name: cradle-api
  namespace: cradle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cradle-api
  template:
    metadata:
      labels:
        app: cradle-api
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker

      initContainers:
        - name: init-create-db
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."
              until mysqladmin ping -h"$DB_HOST" --silent; do
                sleep 2
              done

              echo "Ensuring database exists..."
              mysql -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD" \
                -e "CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;"

              echo "Database check complete."

          envFrom:
            - secretRef:
                name: cradle-secrets

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: cradle-api

      containers:
      - name: cradle-api
        image: ghcr.io/harris-consult/cradle-api:latest
        ports:
        - containerPort: 5001

        envFrom:
        - secretRef:
            name: cradle-secrets
