apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cradle-api-sync
  namespace: cradle
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: cradle-secrets
    creationPolicy: Merge
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        S3_ENDPOINT: "https://s3.churchlify.com"
        S3_BUCKET_NAME: "cradle-data"
        S3_FORCE_PATH_STYLE: "true"
        S3_REGION: "us-east-1"
        DB_NAME: "defaultdb"
        MYSQL_PORT: "3306"
  data:
    - secretKey: DB_USER
      remoteRef:
        key: global-db-secrets 
        property: MYSQL_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: global-db-secrets
        property: MYSQL_PASSWORD
    - secretKey: DB_HOST
      remoteRef:
        key: global-db-secrets
        property: MYSQL_HOST
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: global-db-secrets
        property: MINIO_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: global-db-secrets
        property: MINIO_SECRET_KEY