apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: schoolrider-sync
  namespace: schoolrider
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: schoolrider-secrets
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "mysql://{{ .MYSQL_USER }}:{{ .MYSQL_PASSWORD }}@{{ .MYSQL_HOST }}:3306/schoolrider"
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: global-db-secrets 
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: global-db-secrets
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_HOST
      remoteRef:
        key: global-db-secrets
        property: MYSQL_HOST
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: global-db-secrets
        property: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: global-db-secrets
        property: MINIO_SECRET_KEY