resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/cradle-api
  newName: ghcr.io/harris-consult/cradle-api
  newTag: 48c3316a1156d92446ac6631fa7046de5df06c9b
