resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/cradle-api
  newName: ghcr.io/harris-consult/cradle-api
  newTag: cc148fe5948f67cc2a02b11b4f409aa3aa7d4c5f
