apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schoolrider-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Harris-Consult/gitops.git
    path: apps/schoolrider/api/overlays/production
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: schoolrider
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
