apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colcare-api
  namespace: colcare
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.colcare.com
      secretName: colcare-api-tls
  rules:
    - host: api.colcare.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colcare-api
                port:
                  number: 80
