apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colcare-api-ingress
  namespace: colcare
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.colcare.harrisconsult.org
      secretName: colcare-api-tls
  rules:
    - host: api.colcare.harrisconsult.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colcare-api
                port:
                  number: 80
