apiVersion: batch/v1
kind: Job
metadata:
  name: colcare-prisma-migrate
  namespace: colcare
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/harris-consult/colcare-api:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: colcare-secrets
