apiVersion: batch/v1
kind: Job
metadata:
  name: colcare-migrate
  namespace: colcare
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/harris-consult/colcare-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              npx prisma migrate deploy --schema ./prisma/schema.prisma
          envFrom:
            - secretRef:
                name: colcare-secrets
