resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/colcare-api
  newName: ghcr.io/harris-consult/colcare-api
  newTag: fbeaa9f63484a80696e26797df98070630e180f2
