resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/colcare-api
  newName: ghcr.io/harris-consult/colcare-api
  newTag: 5b488dab66387fdad73b8c08d346922dd24df7a2
