resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/colcare-app
  newName: ghcr.io/harris-consult/colcare-app
  newTag: 7a401da8ebaf6bf0e31454e4a7317d2450690375
