resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/colcare-app
  newName: ghcr.io/harris-consult/colcare-app
  newTag: c082d3f42db544e0299d21d5b1eba903b8a0c272
