resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-api
  newName: ghcr.io/harris-consult/schoolrider-api
  newTag: b3aaefe7b698574604e3fa317617e9c5803ca3c2
