resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-api
  newName: ghcr.io/harris-consult/schoolrider-api
  newTag: 962eca793b7541d5702ae68a0e2358333b157155
