resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/schoolrider-api
  newName: ghcr.io/harris-consult/schoolrider-api
  newTag: 9705c210f92f490fdeb3b1a0efa0728581a0161d
