resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/tkp-traffic-web
  newName: ghcr.io/harris-consult/tkp-traffic-web
  newTag: ccc9fb68dda18927d75cf46c2e1a7fd22b0b2f34
