resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/harris-consult/tkp-traffic-web
  newName: ghcr.io/harris-consult/tkp-traffic-web
  newTag: 10b3564bf69439ab38ea9d2beb10f0f06ff7797f
